spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/reservation;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    data: classpath:populate_data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  