WITH RECURSIVE T(N) AS (
    SELECT 1, GETDATE() AS DATE, TRUE AS AVAILABILITY
    UNION ALL
    SELECT N+1, DATEADD('DAY',N,GETDATE()), TRUE FROM T WHERE N<31
)
INSERT INTO RESERVATION_DATE(DATE, AVAILABILITY)
SELECT DATE, AVAILABILITY FROM T;
